server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital_info?useUnicode=true & characterEncoding=utf-8 &
      useSSL=true & serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    view:
      suffix: .html
  thymeleaf:
    prefix: classpath:/static/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 10MB  #最大提交文件大小
      max-request-size: 100MB

#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: pojo



